Added Poppins font and design system colors
cuappdev/score-android pull request #1
Opened 2024-09-17 18:32 UTC by kelsiliul

Add UI elements.

2024-09-20 03:30 UTC, thisjustin123 requested changes
Please edit the gitignore and git remove the .idea files from the PR!

2024-09-20 03:30 UTC, thisjustin123 commented on .idea/.name
> +Score
`.idea/` files shouldn't be tracked; they should be included in the `.gitignore`. Here's a good template for that:

```
# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Log/OS Files
*.log

# Android Studio generated files and folders
captures/
.externalNativeBuild/
.cxx/
*.apk
output.json

# IntelliJ
*.iml
.idea/
misc.xml
deploymentTargetDropDown.xml
render.experimental.xml

# Keystore files
*.jks
*.keystore

# Google Services (e.g. APIs or Firebase)
app/google-services.json

# Android Profiling
*.hprof

# Secrets
secrets.properties
```

2024-09-20 18:58 UTC, kelsiliul reviewed
Updated .gitignore

2024-09-22 03:26 UTC, thisjustin123 requested changes
I don't see the `.gitignore` changed here? I just see that you git removed the `.idea/` files.

Make sure to actually modify & push the changes to the `.gitignore` file. I gave a good model for what the `.gitignore` file should look like in my previous review.

2024-09-22 05:01 UTC, kelsiliul commented
Updated .gitignore

2024-09-25 21:01 UTC, thisjustin123 approved these changes
Noice 😎

2024-09-25 21:17 UTC, merged